// Fenix
// Also provides workarounds for https://github.com/mozilla-mobile/fenix/issues & Focus
// user_pref("accessibility.typeaheadfind", false);
// user_pref("browser.download.folderList", 2);
// user_pref("browser.urlbar.clickSelectsAll", false);
// user_pref("clipboard.autocopy", false);
// user_pref("dom.disable_beforeunload", true);
// user_pref("dom.event.clipboardevents.enabled", false);
// user_pref("dom.indexedDB.enabled", false);
// user_pref("dom.storage.enabled", false);
// user_pref("font.name-list.emoji", "Noto Color Emoji");
// user_pref("font.name.monospace.ar", "Noto Naskh Arabic");
// user_pref("font.name.monospace.el", "Noto Sans Mono");
// user_pref("font.name.monospace.he", "Noto Sans Hebrew");
// user_pref("font.name.monospace.ja", "Noto Sans CJK JP");
// user_pref("font.name.monospace.ko", "Noto Sans CJK KR");
// user_pref("font.name.monospace.th", "Noto Sans Thai");
// user_pref("font.name.monospace.x-armn", "Noto Sans Armenian");
// user_pref("font.name.monospace.x-beng", "Noto Sans Bengali");
// user_pref("font.name.monospace.x-cans", "monospace");
// user_pref("font.name.monospace.x-cyrillic", "Noto Mono");
// user_pref("font.name.monospace.x-devanagari", "Noto Sans Devanagari");
// user_pref("font.name.monospace.x-ethi", "Noto Sans Ethiopic");
// user_pref("font.name.monospace.x-geor", "Noto Sans Georgian");
// user_pref("font.name.monospace.x-gujr", "Noto Sans Gujarati");
// user_pref("font.name.monospace.x-guru", "Noto Sans Gurmukhi");
// user_pref("font.name.monospace.x-khmr", "Noto Sans Khmer");
// user_pref("font.name.monospace.x-knda", "Noto Sans Kannada");
// user_pref("font.name.monospace.x-math", "Latin Modern Math");
// user_pref("font.name.monospace.x-mlym", "Noto Sans Malayalam");
// user_pref("font.name.monospace.x-orya", "Noto Sans Oriya");
// user_pref("font.name.monospace.x-sinh", "Noto Sans Sinhala");
// user_pref("font.name.monospace.x-tamil", "Noto Sans Tamil");
// user_pref("font.name.monospace.x-telu", "Noto Sans Telugu");
// user_pref("font.name.monospace.x-tibt", "Noto Sans Tibetan");
// user_pref("font.name.monospace.x-unicode", "Noto Mono");
// user_pref("font.name.monospace.x-western", "Noto Mono");
// user_pref("font.name.monospace.zh-CN", "Noto Sans CJK SC");
// user_pref("font.name.monospace.zh-HK", "Noto Sans CJK TC");
// user_pref("font.name.monospace.zh-TW", "Noto Sans CJK TC");
// user_pref("font.name.sans-serif.ar", "Noto Naskh Arabic");
// user_pref("font.name.sans-serif.el", "Noto Sans");
// user_pref("font.name.sans-serif.he", "Noto Sans Hebrew");
// user_pref("font.name.sans-serif.ja", "Noto Sans CJK JP");
// user_pref("font.name.sans-serif.ko", "Noto Sans CJK KR");
// user_pref("font.name.sans-serif.th", "Noto Sans Thai");
// user_pref("font.name.sans-serif.x-armn", "Noto Sans Armenian");
// user_pref("font.name.sans-serif.x-beng", "Noto Sans Bengali");
// user_pref("font.name.sans-serif.x-cans", "sans-serif");
// user_pref("font.name.sans-serif.x-cyrillic", "Noto Sans");
// user_pref("font.name.sans-serif.x-devanagari", "Noto Sans Devanagari");
// user_pref("font.name.sans-serif.x-ethi", "Noto Sans Ethiopic");
// user_pref("font.name.sans-serif.x-geor", "Noto Sans Georgian");
// user_pref("font.name.sans-serif.x-gujr", "Noto Sans Gujarati");
// user_pref("font.name.sans-serif.x-guru", "Noto Sans Gurmukhi");
// user_pref("font.name.sans-serif.x-khmr", "Noto Sans Khmer");
// user_pref("font.name.sans-serif.x-knda", "Noto Sans Kannada");
// user_pref("font.name.sans-serif.x-math", "Latin Modern Math");
// user_pref("font.name.sans-serif.x-mlym", "Noto Sans Malayalam");
// user_pref("font.name.sans-serif.x-orya", "Noto Sans Oriya");
// user_pref("font.name.sans-serif.x-sinh", "Noto Sans Sinhala");
// user_pref("font.name.sans-serif.x-tamil", "Noto Sans Tamil");
// user_pref("font.name.sans-serif.x-telu", "Noto Sans Telugu");
// user_pref("font.name.sans-serif.x-tibt", "Noto Sans Tibetan");
// user_pref("font.name.sans-serif.x-unicode", "Noto Sans");
// user_pref("font.name.sans-serif.x-western", "Noto Sans");
// user_pref("font.name.sans-serif.zh-CN", "Noto Sans CJK SC");
// user_pref("font.name.sans-serif.zh-HK", "Noto Sans CJK TC");
// user_pref("font.name.sans-serif.zh-TW", "Noto Sans CJK TC");
// user_pref("font.name.serif.ar", "Noto Naskh Arabic");
// user_pref("font.name.serif.el", "Noto Serif");
// user_pref("font.name.serif.he", "Noto Serif Hebrew");
// user_pref("font.name.serif.ja", "Noto Serif CJK JP");
// user_pref("font.name.serif.ko", "Noto Serif CJK KR");
// user_pref("font.name.serif.th", "Noto Serif Thai");
// user_pref("font.name.serif.x-armn", "Noto Serif Armenian");
// user_pref("font.name.serif.x-beng", "Noto Serif Bengali");
// user_pref("font.name.serif.x-cans", "serif");
// user_pref("font.name.serif.x-cyrillic", "Noto Serif");
// user_pref("font.name.serif.x-devanagari", "Noto Serif Devanagari");
// user_pref("font.name.serif.x-ethi", "Noto Serif Ethiopic");
// user_pref("font.name.serif.x-geor", "Noto Serif Georgian");
// user_pref("font.name.serif.x-gujr", "Noto Serif Gujarati");
// user_pref("font.name.serif.x-guru", "Noto Serif Gurmukhi");
// user_pref("font.name.serif.x-khmr", "Noto Serif Khmer");
// user_pref("font.name.serif.x-knda", "Noto Serif Kannada");
// user_pref("font.name.serif.x-math", "Latin Modern Math");
// user_pref("font.name.serif.x-mlym", "Noto Serif Malayalam");
// user_pref("font.name.serif.x-orya", "Noto Sans Oriya");
// user_pref("font.name.serif.x-sinh", "Noto Serif Sinhala");
// user_pref("font.name.serif.x-tamil", "Noto Serif Tamil");
// user_pref("font.name.serif.x-telu", "Noto Serif Telugu");
// user_pref("font.name.serif.x-tibt", "Noto Sans Tibetan");
// user_pref("font.name.serif.x-unicode", "Noto Serif");
// user_pref("font.name.serif.x-western", "Noto Serif");
// user_pref("font.name.serif.zh-CN", "Noto Serif CJK SC");
// user_pref("font.name.serif.zh-HK", "Noto Serif CJK TC");
// user_pref("font.name.serif.zh-TW", "Noto Serif CJK TC");
// user_pref("full-screen-api.enabled", false);
// user_pref("general.appname.override", "");
// user_pref("general.appversion.override", "");
// user_pref("general.oscpu.override", "");
// user_pref("general.platform.override", "");
// user_pref("general.useragent.locale", "");
// user_pref("general.useragent.override", "");
// user_pref("general.useragent.site_specific_overrides", false);
// user_pref("general.useragent.updates.lastupdated", "");
// user_pref("identity.fxaccounts.auth.uri", "");
// user_pref("intl.locale.requested", "en-US");
// user_pref("javascript.enabled", false);
// user_pref("keyword.enabled", false);
// user_pref("layers.acceleration.disabled", true);
// user_pref("layers.acceleration.force-enabled", false);
// user_pref("mathml.disabled", true);
// user_pref("media.default_volume", "0.5");
// user_pref("media.media-capabilities.enabled", false);
// user_pref("middlemouse.contentLoadURL", false);
// user_pref("narrate.enabled", false);
// user_pref("network.http.spdy.enabled.deps", false);
// user_pref("network.http.spdy.enabled.http2", false);
// user_pref("network.http.spdy.enabled", false);
// user_pref("network.http.spdy.websockets", false);
// user_pref("network.trr.bootstrapAddress", "");
// user_pref("network.trr.custom_uri", "");
// user_pref("network.trr.mode", 0);
// user_pref("network.trr.uri", "");
// user_pref("nglayout.enable_drag_images", false);
// user_pref("reader.parse-on-load.enabled", false);
// user_pref("security.OCSP.require", true);
// user_pref("security.tls.version.max", 4);
// user_pref("security.tls.version.min", 3);
// user_pref("toolkit.cosmeticAnimations.enabled", false);
// user_pref("view_source.wrap_long_lines", true);
user_pref("accessibility.force_disabled", 1);
user_pref("alerts.showFavicons", false);
user_pref("app.feedback.baseURL", "");
user_pref("app.support.baseURL", "");
user_pref("app.update.autodownload", "never");
user_pref("beacon.enabled", false);
user_pref("breakpad.reportURL", "");
user_pref("browser.bookmarks.max_backups", 3);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.memory.capacity", 0);
user_pref("browser.cache.memory.enable", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.cache.offline.insecure.enable", false);
user_pref("browser.chrome.dynamictoolbar", false);
user_pref("browser.contentblocking.enabled", true);
user_pref("browser.display.use_document_fonts", 0);
user_pref("browser.download.forbid_open_with", true);
user_pref("browser.download.manager.addToRecentDocs", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.fixup.alternate.enabled", false);
user_pref("browser.fixup.alternate.prefix", "");
user_pref("browser.fixup.alternate.suffix", "");
user_pref("browser.formfill.enable", false);
user_pref("browser.formfill.expire_days", 0);
user_pref("browser.helperApps.deleteTempFileOnExit", true);
user_pref("browser.link.open_newwindow", 3);
user_pref("browser.safebrowsing.allowOverride", false);
user_pref("browser.safebrowsing.blockedURIs.enabled", false);
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.phishing.enabled", false);
user_pref("browser.safebrowsing.provider.google.gethashURL", "");
user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", "");
user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", "");
user_pref("browser.safebrowsing.provider.google.reportURL", "");
user_pref("browser.safebrowsing.provider.google.updateURL", "");
user_pref("browser.safebrowsing.provider.google4.dataSharing.enabled", false);
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.safebrowsing.provider.google4.gethashURL", "");
user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", "");
user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", "");
user_pref("browser.safebrowsing.provider.google4.reportURL", "");
user_pref("browser.safebrowsing.provider.google4.updateURL", "");
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
user_pref("browser.safebrowsing.provider.mozilla.lists", "");
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
user_pref("browser.safebrowsing.reportPhishURL", "");
user_pref("browser.search.geoip.timeout", 0);
user_pref("browser.search.geoip.url", "");
user_pref("browser.search.geoSpecificDefaults.url", "");
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.region", "US");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.send_pings.max_per_link", 0);
user_pref("browser.send_pings.require_same_host", true);
user_pref("browser.send_pings", false);
user_pref("browser.sessionhistory.max_entries", 10);
user_pref("browser.sessionhistory.max_total_viewers", 0);
user_pref("browser.sessionstore.interval", 70000);
user_pref("browser.sessionstore.max_tabs_undo", 10);
user_pref("browser.sessionstore.privacy_level", 2);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.snippets.enabled", false);
user_pref("browser.snippets.firstrunHomepage.enabled", false);
user_pref("browser.snippets.geoUrl", "");
user_pref("browser.snippets.statsUrl", "");
user_pref("browser.snippets.syncPromo.enabled", false);
user_pref("browser.snippets.updateInterval", 0);
user_pref("browser.snippets.updateUrl", "");
user_pref("browser.ssl_override_behavior", 2);
user_pref("browser.tabs.remote.allowLinkedWebInFileUriProcess", false);
user_pref("browser.tabs.remote.autostart", true);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("browser.urlbar.trimURLs", false);
user_pref("browser.xul.error_pages.expert_bad_cert", true);
user_pref("canvas.capturestream.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("device.sensors.enabled", false);
user_pref("device.storage.enabled", false)
user_pref("devtools.chrome.enabled", false);
user_pref("devtools.debugger.logging", false);
user_pref("devtools.debugger.remote-enabled", false);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.onboarding.telemetry.logged", false);
user_pref("devtools.remote.usb.enabled", true);
user_pref("devtools.remote.wifi.scan", false);
user_pref("devtools.webide.enabled", true);
user_pref("dom.allow_cut_copy", false); // Hidden preference
user_pref("dom.allow_scripts_to_close_windows", true);
user_pref("dom.battery.enabled", false);
user_pref("dom.caches.enabled", false);
user_pref("dom.disable_open_during_load", true);
user_pref("dom.disable_window_flip", true);
user_pref("dom.disable_window_move_resize", true);
user_pref("dom.disable_window_open_feature.close", true);
user_pref("dom.disable_window_open_feature.location", true);
user_pref("dom.disable_window_open_feature.menubar", true);
user_pref("dom.disable_window_open_feature.minimizable", true);
user_pref("dom.disable_window_open_feature.personalbar", true);
user_pref("dom.disable_window_open_feature.resizable", true);
user_pref("dom.disable_window_open_feature.status", true);
user_pref("dom.disable_window_open_feature.toolbar", true);
user_pref("dom.enable_performance_navigation_timing", false);
user_pref("dom.enable_performance_observer", false);
user_pref("dom.enable_performance", false);
user_pref("dom.enable_resource_timing", false);
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("dom.event.highrestimestamp.enabled", true);
user_pref("dom.fileHandle.enabled", false);
user_pref("dom.forms.datetime.others", false);
user_pref("dom.forms.datetime.timepicker", false);
user_pref("dom.forms.datetime", false);
user_pref("dom.gamepad.enabled", false);
user_pref("dom.gamepad.extensions.enabled", false);
user_pref("dom.gamepad.haptic_feedback.enabled", false);
user_pref("dom.gamepad.test.enabled", false);
user_pref("dom.imagecapture.enabled", false);
user_pref("dom.indexedDB.experimental", false);
user_pref("dom.indexedDB.logging.details", false);
user_pref("dom.indexedDB.logging.enabled", false);
user_pref("dom.indexedDB.logging.profiler-marks", false);
user_pref("dom.IntersectionObserver.enabled", false);
user_pref("dom.ipc.plugins.flash.subprocess.crashreporter.enabled", false);
user_pref("dom.ipc.plugins.reportCrashURL", false);
user_pref("dom.netinfo.enabled", false);
user_pref("dom.performance.enable_scheduler_timing", false);
user_pref("dom.performance.enable_user_timing_logging", false);
user_pref("dom.popup_allowed_events", "click dblclick");
user_pref("dom.popup_maximum", 3);
user_pref("dom.push.connection.enabled", false);
user_pref("dom.push.enabled", false);
user_pref("dom.push.serverURL", "");
user_pref("dom.push.userAgentID", "");
user_pref("dom.serviceWorkers.enabled", false);
user_pref("dom.storageManager.enabled", false);
user_pref("dom.targetBlankNoOpener.enabled", true);
user_pref("dom.vibrator.enabled", false);
user_pref("dom.vr.enabled", false);
user_pref("dom.vr.service.enabled", false);
user_pref("dom.w3c_pointer_events.enabled", false);
user_pref("dom.w3c_touch_events.enabled", 0);
user_pref("dom.webaudio.enabled", false);
user_pref("dom.webnotifications.enabled", false);
user_pref("dom.webnotifications.serviceworker.enabled", false);
user_pref("extensions.autoDisableScopes", 15);
user_pref("extensions.autoupdate.enabled", false);
user_pref("extensions.blocklist.url", "https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%20/%20/");
user_pref("extensions.enabledScopes", 1);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.getAddons.search.browseURL", "https://addons.mozilla.org/%LOCALE%/android/search?q=%TERMS%");
user_pref("extensions.logging.enabled", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.webcompat-reporter.enabled", false);
user_pref("extensions.webcompat-reporter.newIssueEndpoint", "");
user_pref("extensions.webextensions.enablePerformanceCounters", false);
user_pref("extensions.webextensions.restrictedDomains", "");
user_pref("full-screen-api.warning.delay", 0);
user_pref("full-screen-api.warning.timeout", 0);
user_pref("general.warnOnAboutConfig", false);
user_pref("geo.enabled", false);
user_pref("gfx.font_rendering.graphite.enabled", false);
user_pref("gfx.logging.painted-pixel-count.enabled", false);
user_pref("gfx.logging.peak-texture-usage.enabled", false);
user_pref("gfx.logging.texture-usage.enabled", false);
user_pref("gfx.offscreencanvas.enabled", false);
user_pref("home.sync.updateMode", 0);
user_pref("intl.accept_languages", "en-US, en");
user_pref("intl.charset.detector", "");
user_pref("intl.locale.requested", "en-US");
user_pref("intl.regional_prefs.use_os_locales", false);
user_pref("javascript.options.asmjs", false);
user_pref("javascript.options.wasm", false);
user_pref("layout.css.clip-path-shapes.enabled", false);
user_pref("layout.css.visited_links_enabled", false);
user_pref("layout.spellcheckDefault", 2);
user_pref("media.autoplay.allow-muted", false);
user_pref("media.autoplay.ask-permission", true);
user_pref("media.autoplay.block-event.enabled", true);
user_pref("media.autoplay.block-webaudio", true);
user_pref("media.autoplay.default", 1);
user_pref("media.autoplay.default", 2);
user_pref("media.av1.enabled", true);
user_pref("media.block-autoplay-until-in-foreground", true);
user_pref("media.block-autoplay-until-in-foreground", true);     
user_pref("media.eme.enabled", false);
user_pref("media.getusermedia.agc_enabled", false);
user_pref("media.getusermedia.audiocapture.enabled", false);
user_pref("media.getusermedia.browser.enabled", false);
user_pref("media.getusermedia.noise_enabled", false);
user_pref("media.gmp-gmpopenh264.autoupdate", false); 
user_pref("media.gmp-gmpopenh264.enabled", false);
user_pref("media.gmp-manager.buildID", "");
user_pref("media.gmp-manager.cert.checkAttributes", false);
user_pref("media.gmp-manager.cert.requireBuiltIn", false);
user_pref("media.gmp-manager.certs.1.commonName", "");
user_pref("media.gmp-manager.certs.1.issuerName", "");
user_pref("media.gmp-manager.certs.2.commonName", "");
user_pref("media.gmp-manager.certs.2.issuerName", "");
user_pref("media.gmp-manager.lastCheck", "");
user_pref("media.gmp-manager.updateEnabled", false);
user_pref("media.gmp-manager.url.override", "data:text/plain,");
user_pref("media.gmp-manager.url", "data:text/plain,");
user_pref("media.gmp-provider.enabled", false);
user_pref("media.gmp.trial-create.enabled", false);
user_pref("media.mediasource.webm.enabled", true);
user_pref("media.navigator.enabled", false);
user_pref("media.navigator.mediadatadecoder_h264_enabled", false);
user_pref("media.navigator.video.enabled", false);
user_pref("media.ondevicechange.enabled", false);
user_pref("media.peerconnection.dtmf.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("media.peerconnection.ice.no_host", true);
user_pref("media.peerconnection.ice.tcp", false);
user_pref("media.peerconnection.identity.enabled", false);
user_pref("media.peerconnection.identity.timeout", 1);
user_pref("media.peerconnection.rtpsourcesapi.enabled", false);
user_pref("media.peerconnection.simulcast", false);
user_pref("media.peerconnection.turn.disable", true);
user_pref("media.peerconnection.use_document_iceservers", false);
user_pref("media.peerconnection.video.enabled", false);
user_pref("media.plugins.enabled", false);
user_pref("media.video_stats.enabled", false);
user_pref("media.webspeech.recognition.enable", false);
user_pref("media.webspeech.synth.enabled", false);
user_pref("network.allow-experiments", false);
user_pref("network.auth.subresource-http-auth-allow", 1);
user_pref("network.auth.subresource-img-cross-origin-http-auth-allow", false);
user_pref("network.captive-portal-service.enabled", true);
user_pref("network.captive-portal-service.minInterval", 35);
user_pref("network.connectivity-service.DNSv4.domain", "");
user_pref("network.connectivity-service.DNSv6.domain", "");
user_pref("network.connectivity-service.enabled", false);
user_pref("network.connectivity-service.IPv4.url", "");
user_pref("network.connectivity-service.IPv6.url", "");
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.leave-secure-alone", true);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.same-site.enabled", true);
user_pref("network.cookie.thirdparty.nonsecureSessionOnly", true);
user_pref("network.cookie.thirdparty.sessionOnly", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.dns.disablePrefetchFromHTTPS", true);
user_pref("network.http.altsvc.enabled", false);
user_pref("network.http.altsvc.oe", false);
user_pref("network.http.redirection-limit", 10);
user_pref("network.http.referer.defaultPolicy.pbmode", 2);
user_pref("network.http.referer.defaultPolicy", 3);
user_pref("network.http.referer.hideOnionSource", false);
user_pref("network.http.referer.spoofSource", true);
user_pref("network.http.referer.trimmingPolicy", 0);
user_pref("network.http.referer.XOriginPolicy", 1);
user_pref("network.http.referer.XOriginTrimmingPolicy", 0);
user_pref("network.http.sendRefererHeader", 2);
user_pref("network.http.speculative-parallel-limit", "0");
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.IDN_show_punycode", true);
user_pref("network.notify.changed", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enable-hover-on-ssl", false);
user_pref("network.predictor.enable-prefetch", false);
user_pref("network.predictor.enabled", false);
user_pref("network.predictor.preconnect-min-confidence", 101);
user_pref("network.predictor.prefetch-min-confidence", 101);
user_pref("network.predictor.prefetch-rolling-load-count", 0);
user_pref("network.predictor.preresolve-min-confidence", 101);
user_pref("network.prefetch-next", false);
user_pref("network.preload", false);
user_pref("network.proxy.autoconfig_url.include_path", false);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.security.ports.banned", "9050,9051,9150,9151");
user_pref("network.tickle-wifi.enabled", false);
user_pref("network.warnOnAboutNetworking", false);
user_pref("offline-apps.allow_by_default", false);
user_pref("plugin.default.state", 0);
user_pref("plugin.disable", false);
user_pref("plugin.sessionPermissionNow.intervalInMinutes", 0);
user_pref("plugins.click_to_play", true);
user_pref("privacy.donottrackheader.enabled", false);
user_pref("privacy.firstparty.isolate.restrict_opener_access", true);
user_pref("privacy.firstparty.isolate", true);
user_pref("privacy.resistFingerprinting.block_mozAddonManager", true);
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.trackingprotection.enabled",	false);
user_pref("privacy.trackingprotection.enabled", false);
user_pref("privacy.trackingprotection.introURL", "");
user_pref("privacy.trackingprotection.pbmode.enabled", false);
user_pref("private.data.cookies_sessions
user_pref("security.ask_for_password", 2);
user_pref("security.cert_pinning.enforcement_level", 2);
user_pref("security.csp.enable_violation_events", false);
user_pref("security.csp.enable", true);
user_pref("security.csp.experimentalEnabled", false);
user_pref("security.data_uri.block_toplevel_data_uri_navigations", true);
user_pref("security.dialog_enable_delay", 0);
user_pref("security.family_safety.mode", 0);
user_pref("security.insecure_field_warning.contextual.enabled", true);
user_pref("security.mixed_content.block_active_content", true);
user_pref("security.mixed_content.block_display_content", true);
user_pref("security.mixed_content.block_object_subrequest", true);
user_pref("security.OCSP.enabled", 1);
user_pref("security.OCSP.require", true);
user_pref("security.password_lifetime", 5);
user_pref("security.pki.distrust_ca_policy", 2);
user_pref("security.pki.sha1_enforcement_level", 1);
user_pref("security.sandbox.logging.enabled", false);
user_pref("security.ssl.disable_session_identifiers", true);
user_pref("security.ssl.enable_ocsp_must_staple", true);
user_pref("security.ssl.enable_ocsp_stapling", true);
user_pref("security.ssl.errorReporting.automatic", false);
user_pref("security.ssl.errorReporting.enabled", false);
user_pref("security.ssl.errorReporting.url", "");
user_pref("security.ssl.require_safe_negotiation", true);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);
user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.rsa_des_ede3_sha", false);
user_pref("security.tls.enable_0rtt_data", false);
user_pref("security.tls.version.fallback-limit", 3);
user_pref("signon.autofillForms.http", false);
user_pref("signon.autofillForms", false);
user_pref("signon.formlessCapture.enabled", false);
user_pref("signon.rememberSignons", false);
user_pref("signon.storeWhenAutocompleteOff", true);
user_pref("toolkit.telemetry.debugSlowSql", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.server", "data:,");
user_pref("toolkit.telemetry.unified", false);
user_pref("ui.use_standins_for_native_colors", true);
user_pref("urlclassifier.blockedTable", "");
user_pref("urlclassifier.disallow_completions", "");
user_pref("urlclassifier.downloadAllowTable", "");
user_pref("urlclassifier.downloadBlockTable", "");
user_pref("urlclassifier.flashAllowExceptTable", "");
user_pref("urlclassifier.flashAllowTable", "");
user_pref("urlclassifier.flashExceptTable", "");
user_pref("urlclassifier.flashSubDocExceptTable", "");
user_pref("urlclassifier.flashSubDocTable", "");
user_pref("urlclassifier.flashTable", "");
user_pref("urlclassifier.malwareTable", "");
user_pref("urlclassifier.passwordAllowTable", "");
user_pref("urlclassifier.phishTable", "");
user_pref("urlclassifier.trackingTable", "");
user_pref("urlclassifier.trackingWhitelistTable", "");
user_pref("webchannel.allowObject.urlWhitelist", "");
user_pref("webgl.disable-extensions", true);
user_pref("webgl.disable-fail-if-major-performance-caveat", true);
user_pref("webgl.disabled", true);
user_pref("webgl.enable-debug-renderer-info", false);
user_pref("webgl.enable-webgl2", false);
user_pref("webgl.force-enabled", false);
user_pref("webgl.min_capability_mode", true);
user_pref("webgl.msaa-force", false);
user_pref("xpinstall.whitelist.required", true);
